import { HeroSection } from '@/components/home';
import { AdminLayout, MainLayout } from '@/components/layout';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn mui UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <h1>This is homepage</h1>
        <Link href="/about">About us</Link>

        <HeroSection />
      </div>
    </>
  );
}

Home.Layout = MainLayout;
