import { Seo } from '@/components/common';
import { FeatureWorks, HeroSection, RecentPosts } from '@/components/home';
import { MainLayout } from '@/components/layout';
import { Box } from '@mui/material';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn mui UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box>
        <Seo
          data={{
            title: 'NextJS Tutorials | Easy Frontend',
            description:
              'Step by step tutorials to build a full CRUD website using NextJS for beginners',
            url: 'https://learn-nextjs-fawn.vercel.app/',
            thumbnailUrl:
              'https://cdn.getshifter.co/caa65008efb706a8bfc6f7e4045d6a018420c3df/uploads/2020/11/nextjs.png',
          }}
        />
        <HeroSection />
        <RecentPosts />
        <FeatureWorks />
      </Box>
    </>
  );
}

Home.Layout = MainLayout;
